version: '3'

services:
  swarm-manager:
    image: cryptokasm/9c-swarm-manager:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DEBUG=1
      - DEV_MODE=true
      - PRIVATE_KEY=DEMO
  kosmic-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:80'
